parameters:
  downloader_list:
    dilbert: App\Downloader\Dilbert\Downloader
    xkcd: App\Downloader\XKCD\Downloader
    maliki: App\Downloader\Maliki\Downloader
    commitstrip: App\Downloader\CommitStrip\Downloader
    gantz: App\Downloader\Gantz\Downloader
    naruto: App\Downloader\Naruto\Downloader
    fairy-tail: App\Downloader\FairyTail\Downloader
    cyanide: App\Downloader\CyanideHappiness\Downloader
  mime_type_list:
    image/gif: .gif
    image/png: .png
    image/bmp: .bmp
    image/jpeg: .jpg
    image/tiff: .tiff
